GCLOUD_LOCATION: "us-central1"
GCLOUD_PROJECT_ID: "specialtopicsai"
BACKEND_URL: "http://localhost:8081/chat"
STORAGE_BUCKET_NAME: "personal-expense-assistant-receipts"
DB_COLLECTION_NAME: "personal-expense-assistant-receipts"